services:
  # Servizio Database In-Memory
  # Se il bot gira in un sistema operativo Linux la prima volta che si avvia, usare:
  # sudo sysctl vm.overcommit_memory=1 && echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf
  # Questa impostazione Kernel sulla macchina che ospita i container serve a non fermare Redis 
  # in caso di lavoro intenso.
  # i.e. cautelativamente redis chiede troppa RAM e il kernel lo ferma, però è molto improbabile redis la usi tutta
  redis:
    image: redis:7-alpine
    container_name: pipster_redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Il nostro Bot
  bot:
    build: .
    image: pipster
    container_name: pipster_bot
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./reports:/app/reports
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Comando standard: avvia il bot normalmente
    command: python main.py
    restart: unless-stopped

volumes:
  redis_data: