services:
  redis:
    # Cambiamo l'immagine per includere i moduli RedisJSON e RedisSearch
    image: redis/redis-stack-server:latest
    container_name: pipster_redis
    #command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  bot:
    build: .
    image: pipster
    container_name: pipster_bot
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./reports:/app/reports
      # Aggiungiamo il volume per i dati storici (Parquet)
      - ./historical_data:/app/historical_data
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYDEVD_DISABLE_FILE_VALIDATION=1  # Toglie il warning del debugger
      - PYTHONUNBUFFERED=1               # Log in tempo reale (fondamentale), ora vedi i print mano a mano che compaiono
    # Se vuoi togliere anche il warning su "frozen modules", 
    # dovresti aggiungere -Xfrozen_modules=off al comando python
    # Comando standard: avvia il bot normalmente
    command: python main.py
    restart: unless-stopped

volumes:
  redis_data: